name: .NET

on:
  push:
    branches: [ "TLang" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Show repo (debug)
      run: |
        echo "List root"
        ls -la
        echo "List ProjectShop.Server"
        ls -la ProjectShop.Server

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ProjectShop.Server

    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ProjectShop.Server

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ProjectShop.Server

    - name: Build client (optional) - React/TS
      if: always()
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install & build client
      if: always()
      run: |
        cd projectshop.client
        npm ci
        npm run build
